frontend:
- changed-files:
  - any-glob-to-any-file:
    - 'web/themes/**'
    - '**/*.css'
    - '**/*.scss'
    - '**/*.js'

backend:
- changed-files:
  - any-glob-to-any-file:
    - 'web/modules/custom/**'
    - '**/*.php'

config:
- changed-files:
  - any-glob-to-any-file: 'config/**'

infra:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**'
    - 'pantheon.yml'
    - 'pantheon.upstream.yml'
    - '.lando.yml'
    - '.ddev/**'